[build-system]
requires = [
    "setuptools>=80",
    "wheel",
    "setuptools-scm>=8,<9",
]
build-backend = "setuptools.build_meta"


[project]
name = "information-matching"
dynamic = ["version"]
description = "Information-matching method of optimal experimental design and active learning"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Yonatan Kurniawan", email = "kurniawanyo@outlook.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "numpy",
    "scipy",
    "numdifftools",
    "cvxpy",
    "sdpa-python",
    "wget",
]


[project.urls]
Homepage = "https://github.com/yonatank93/information-matching"
Repository = "https://github.com/yonatank93/information-matching"


[project.optional-dependencies]
test = [
    "pytest",
]

dev = [
    "pytest",
    "jupyter",
    "matplotlib",
    "pyqt5",
]


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["."]
exclude = [
    "tests*",
    "examples*",
    "theory*",
]


[tool.setuptools_scm]
version_file = "information_matching/_version.py"


[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]